// Auth errors (401/403)
export const AUTH_TOKEN_INVALID = 'AUTH_TOKEN_INVALID';
export const AUTH_TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED';
export const AUTH_INSUFFICIENT_ROLE = 'AUTH_INSUFFICIENT_ROLE';
export const AUTH_CITY_ACCESS_DENIED = 'AUTH_CITY_ACCESS_DENIED';

// Validation errors (400)
export const VALIDATION_INVALID_INPUT = 'VALIDATION_INVALID_INPUT';
export const VALIDATION_MISSING_REQUIRED = 'VALIDATION_MISSING_REQUIRED';

// Business errors (422)
export const BUSINESS_CITY_ALREADY_EXISTS = 'BUSINESS_CITY_ALREADY_EXISTS';
export const BUSINESS_CITY_NOT_FOUND = 'BUSINESS_CITY_NOT_FOUND';
export const BUSINESS_CITY_INACTIVE = 'BUSINESS_CITY_INACTIVE';
export const BUSINESS_INVALID_CONFIG = 'BUSINESS_INVALID_CONFIG';
export const BUSINESS_FEE_SCHEDULE_CONFLICT = 'BUSINESS_FEE_SCHEDULE_CONFLICT';
export const BUSINESS_PROCESS_PENDING_APPROVAL = 'BUSINESS_PROCESS_PENDING_APPROVAL';
export const BUSINESS_FRANCHISE_APPLICATION_INVALID_STATUS = 'BUSINESS_FRANCHISE_APPLICATION_INVALID_STATUS';
export const BUSINESS_FRANCHISE_NOT_FOUND = 'BUSINESS_FRANCHISE_NOT_FOUND';
export const BUSINESS_AGENT_NOT_FOUND = 'BUSINESS_AGENT_NOT_FOUND';
export const BUSINESS_DEALER_NOT_FOUND = 'BUSINESS_DEALER_NOT_FOUND';
export const BUSINESS_INSUFFICIENT_TRANSACTIONS = 'BUSINESS_INSUFFICIENT_TRANSACTIONS';
export const BUSINESS_EXPORT_TOO_LARGE = 'BUSINESS_EXPORT_TOO_LARGE';
export const BUSINESS_TRAINING_SCORE_TOO_LOW = 'BUSINESS_TRAINING_SCORE_TOO_LOW';
export const BUSINESS_AUDIT_INVALID_STATUS = 'BUSINESS_AUDIT_INVALID_STATUS';

// System errors (500)
export const SYSTEM_INTERNAL_ERROR = 'SYSTEM_INTERNAL_ERROR';
export const SYSTEM_DATABASE_ERROR = 'SYSTEM_DATABASE_ERROR';
export const SYSTEM_BIGQUERY_SYNC_FAILED = 'SYSTEM_BIGQUERY_SYNC_FAILED';
